### ISSUE TITLE
[TODO] Add security policy

### ISSUE THREAD

**Issue by kokonut27** [TheIoLang/mailserver#6]
Add security policy for mail server just in case.

> Assigned for @DillonB07

**Comment by transcental** [comment]
Ok.

People _can_ spam the server. But maybe not as I added reCAPTCHA.

And the emails are all in secrets so it **_should_** be fine.

**Comment by kokonut27** [comment]
Got it, thanks for letting me know!

**Comment by kokonut27** [comment]
I'll just close this for now.
